#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jdk-aether
Version  : 1.0.2.v20150114
Release  : 4
URL      : https://github.com/eclipse/aether-core/archive/aether-1.0.2.v20150114.tar.gz
Source0  : https://github.com/eclipse/aether-core/archive/aether-1.0.2.v20150114.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 EPL-1.0
Requires: jdk-aether-data
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-apache-parent
BuildRequires : jdk-aqute-bndlib
BuildRequires : jdk-atinject
BuildRequires : jdk-bsh
BuildRequires : jdk-build-helper-maven-plugin
BuildRequires : jdk-cdi-api
BuildRequires : jdk-commons-beanutils
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-digester
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-commons-validator
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-eclipse-eclipse
BuildRequires : jdk-eclipse-osgi
BuildRequires : jdk-eclipse-osgi-services
BuildRequires : jdk-enforcer
BuildRequires : jdk-felix
BuildRequires : jdk-felix-bundlerepository
BuildRequires : jdk-felix-framework
BuildRequires : jdk-felix-osgi-foundation
BuildRequires : jdk-felix-utils
BuildRequires : jdk-glassfish-servlet-api
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-hamcrest
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-jdom
BuildRequires : jdk-jetty
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-junit4
BuildRequires : jdk-kxml
BuildRequires : jdk-log4j
BuildRequires : jdk-logback
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-bundle-plugin
BuildRequires : jdk-maven-common-artifact-filters
BuildRequires : jdk-maven-compiler-plugin
BuildRequires : jdk-maven-dependency-tree
BuildRequires : jdk-maven-filtering
BuildRequires : jdk-maven-invoker
BuildRequires : jdk-maven-jar-plugin
BuildRequires : jdk-maven-javadoc-plugin
BuildRequires : jdk-maven-plugin-testing
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-reporting-impl
BuildRequires : jdk-maven-resources-plugin
BuildRequires : jdk-maven-shared-incremental
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-osgi-compendium
BuildRequires : jdk-osgi-core
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-cli
BuildRequires : jdk-plexus-compiler
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interactivity
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-qdox
BuildRequires : jdk-sisu
BuildRequires : jdk-sisu-mojos
BuildRequires : jdk-slf4j
BuildRequires : jdk-snappy-java
BuildRequires : jdk-surefire
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn

%description
Homepage
========
<http://www.eclipse.org/aether/>
License
=======
- [Eclipse Public License, v1.0](http://www.eclipse.org/legal/epl-v10.html)

%package data
Summary: data components for the jdk-aether package.
Group: Data

%description data
data components for the jdk-aether package.


%prep
%setup -q -n aether-core-aether-1.0.2.v20150114

python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :clirr-maven-plugin
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :clirr-maven-plugin aether-api
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :clirr-maven-plugin aether-util
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :clirr-maven-plugin aether-spi
for module in aether-api aether-connector-basic aether-impl   \
aether-spi aether-test-util aether-transport-file \
aether-transport-classpath aether-transport-http  \
aether-transport-wagon aether-util; do
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :animal-sniffer-maven-plugin $module
done
rm -rf aether-transport-http/src/test
python3 /usr/share/java-utils/pom_editor.py pom_xpath_remove "pom:dependency[pom:scope='test']" aether-transport-http
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :maven-enforcer-plugin

%build
python3 /usr/share/java-utils/mvn_build.py -s

%install
xmvn-install  -R .xmvn-reactor -n aether -d %{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/aether/aether-api.jar
/usr/share/java/aether/aether-connector-basic.jar
/usr/share/java/aether/aether-impl.jar
/usr/share/java/aether/aether-spi.jar
/usr/share/java/aether/aether-test-util.jar
/usr/share/java/aether/aether-transport-classpath.jar
/usr/share/java/aether/aether-transport-file.jar
/usr/share/java/aether/aether-transport-http.jar
/usr/share/java/aether/aether-transport-wagon.jar
/usr/share/java/aether/aether-util.jar
/usr/share/maven-metadata/aether-aether-api.xml
/usr/share/maven-metadata/aether-aether-connector-basic.xml
/usr/share/maven-metadata/aether-aether-impl.xml
/usr/share/maven-metadata/aether-aether-spi.xml
/usr/share/maven-metadata/aether-aether-test-util.xml
/usr/share/maven-metadata/aether-aether-transport-classpath.xml
/usr/share/maven-metadata/aether-aether-transport-file.xml
/usr/share/maven-metadata/aether-aether-transport-http.xml
/usr/share/maven-metadata/aether-aether-transport-wagon.xml
/usr/share/maven-metadata/aether-aether-util.xml
/usr/share/maven-metadata/aether-aether.xml
/usr/share/maven-poms/aether/aether-api.pom
/usr/share/maven-poms/aether/aether-connector-basic.pom
/usr/share/maven-poms/aether/aether-impl.pom
/usr/share/maven-poms/aether/aether-spi.pom
/usr/share/maven-poms/aether/aether-test-util.pom
/usr/share/maven-poms/aether/aether-transport-classpath.pom
/usr/share/maven-poms/aether/aether-transport-file.pom
/usr/share/maven-poms/aether/aether-transport-http.pom
/usr/share/maven-poms/aether/aether-transport-wagon.pom
/usr/share/maven-poms/aether/aether-util.pom
/usr/share/maven-poms/aether/aether.pom
